### ISSUE TITLE
Preconfigured shared calendar not imported

### ISSUE THREAD

**Issue by incastrix** [texxasrulez/Caldav_Calendar#14]
If there is a shared calendar via calendar-proxy-read or calendar-proxy-write, the first user that access RC view it in calendars list, the others not.

the problem is in how the plugin check for new calendars:
https://github.com/texxasrulez/Caldav_Calendar/blob/e4184a68f60384b0bf85037d5c3e27348dbc11fc/calendar/drivers/caldav/caldav_driver.php#L160

check only if  this calendar is caldav_calendars table, instead of checking calendar and user

select * from caldav_calendars inner join users on caldav_calendars.user_id = users.user_id where caldav_url LIKE ? and users.username = ?

**Comment by texxasrulez** [comment]
To be honest, I do not understand this issue. Proxy from where? I will close in a few days if submitter does not clarify.

**Comment by trogper** [comment]
I have the same issue. The mentioned line is about skipping calendars, which are already configured.
The issue is, that it checks only the URL, not URL and User, so when you add a new calendar with the same URL as some other user has, it is not added. 
I have expirienced it when adding calendars manually, I just append `?asd` to the url when adding and remove it it afterwards

**Comment by texxasrulez** [comment]
I still don't understand. The URL has the username within it, so there cannot be URL's that are exactly the same between different users on Nextcloud. 
Please provide detailed information to help me figure this out. Log files, screen captures or anything else you can provide to help clarify this issue and get it resolved.

**Comment by trogper** [comment]
When adding a nextcloud calendar, sure. But not when adding other calendar, such as from davical, which doesn't use username as a part of URL.
Otherwise, there is no error when collision is detected, so the form is submitted, accepted and calendar is silently not added

**Comment by texxasrulez** [comment]
Yeah, this is only meant to work with Nextcloud. I started this because the caldav calendars available at the time would not work with Nextcloud, so I forked it to make this one Nextcloud friendly. I do not have the time or even every possible incantation of caldav installed to test and code for it. I actually don't even have my server up and hosting, I am the IT Nerd/King at my work, so I have a sandbox setup on their hosted server to play in. I has been almost 3 years since I moved to California from Texas and my ISP will not give me a public IP so I can host from home and I do MISS THE HECK OUT OF IT. I was very active in the [i-MSCP](https://github.com/i-MSCP/imscp) Community until my move and truly miss that as I was excited to actually be a part of something that just kept getting better . 

Anyway I digress, sorry but I am an old man, and I do wish that I could make this compatible with any and all versions of caldav flavors out there. I have asked for help in doing just that very thing but have had no takers yet. I would devote the time I spend on this to something like that if I had help. It certainly would come together real fast if that would happen. If you, or anyone you know would like to work on something like that, contact me and we can Get'r Started. Until then, I will keep this closed as an issue since I do specify in the Readme this version is for Nextcloud only. 

I do thank you for your interest and lets make something better for all ... Peace and have a great day
