### ISSUE TITLE
loop/timeout while loading calendar

### ISSUE THREAD

**Issue by bahnfrei** [texxasrulez/Caldav_Calendar#37]
Hi,

i tried to get this working with roundcube 1.4-rc2, php-7.1 and baikal dav server. the connection to baikal dav server seems to work, but the plugin hangs while loading/synching:

````
caldav_driver: Found new event /baikal/dav.php/calendars/familie/default/0k7bcb0blarkurd0u1in22vqod@google.com.ics
caldav_driver: Found new event /baikal/dav.php/calendars/familie/default/b065cb79-6a39-4189-a019-4d5b24da283f.1552318713525.ics
...
PHP Fatal error:  Maximum execution time of 120 seconds exceeded in plugins/calendar/drivers/caldav/caldav_driver.php on line 676
PHP Fatal error:  Maximum execution time of 120 seconds exceeded in plugins/calendar/drivers/caldav/caldav_driver.php on line 675
````

do you have any idea, what's going wrong here?

Thanks a lot!

**Comment by texxasrulez** [comment]
I do not know enough about baikal to be of help. This is intended for use with Nextcloud calendar only. Sorry but do not have time to expand supported compatible alternatives to Nextcloud.

**Comment by helmut72** [comment]
I'm getting the same error messages and loop loading my calendars from Nextcloud.

```
[26-Jan-2020 09:47:14 Europe/Berlin] PHP Fatal error:  Maximum execution time of 120 seconds exceeded in /var/www/html/plugins/calendar/drivers/caldav/caldav_driver.php on line 671
[26-Jan-2020 09:48:10 Europe/Berlin] PHP Fatal error:  Maximum execution time of 120 seconds exceeded in /var/www/html/plugins/calendar/drivers/caldav/caldav_driver.php on line 671
[26-Jan-2020 09:49:30 Europe/Berlin] PHP Fatal error:  Maximum execution time of 120 seconds exceeded in /var/www/html/plugins/calendar/drivers/caldav/caldav_driver.php on line 670
[26-Jan-2020 09:50:40 Europe/Berlin] PHP Fatal error:  Maximum execution time of 120 seconds exceeded in /var/www/html/plugins/calendar/drivers/caldav/caldav_driver.php on line 670
[26-Jan-2020 09:51:50 Europe/Berlin] PHP Fatal error:  Maximum execution time of 120 seconds exceeded in /var/www/html/plugins/calendar/drivers/caldav/caldav_driver.php on line 670

```

Using Roundcube 1.4.2, PHP 7.3, Nextcloud 18.0.0 and Calendar Plugin for RC1.4.1

Also Webinterface of Roundcube hangs in Calendar while showing "loading" or "updating". Can't switch to Mail, Contacts...

**Comment by texxasrulez** [comment]
You have to configure your PHP for more power. This error is specific to your php_value max_execution_time value, but I also recommend you customize all the variables that you can. I don't know if you are on shared hosting, not that easy or even allowed on shared hosted plans depending on your provider. If you are not familiar with PHP, go to their official [site](https://www.php.net/) and there are tutorials there that will help you unleash the true power of PHP.

Sorry, but not an issue with plugin

**Comment by helmut72** [comment]
PHP settings works for Roundcube (+Carddav Plugin), Nextcloud, Grav, Filerun, Piwigo, Tiny Tiny RSS, but not for the Caldav Plugin, which also stops user interaction while try to load my few calendar entries from Nextcloud.

**Comment by texxasrulez** [comment]
I have had this very issue in the past and almost exact error and that was from the calendar plugin I was using from FasterIT AwesomeIT before I ever forked it and started working on my own version. The calendar plugin is a resource hog. especially if you have lots of events and calendars running on a not so hot server, it takes quite some time to sync between the frontend and backend. Right now, I have one calendar, with maybe 20 events on my testing box, which is basically a desktop PC with 128MB of ram running Debian as a HTTP, FTP, MAIL, PHP, SQL, CALDAV and CLOUD server all on one machine and that takes about 15-30 seconds to sync. In the past, when I ran into the problem you have now,  all my plugins worked well too and I have used blind-coders carddav plugin since it was released, with hundreds of contacts and the calendar plugin with 5 different calendars and thousands of events is when I first got the max execution error every time I tried to sync my calendar plugin, until I tweaked my PHP settings and that was supposedly hosted on a killer server at a hosting company that shall remain nameless. That is when I first starting building my own servers out of old used desktops using linux (Debian mostly) to host with, as hosting providers don't let you tweak much, if anything at all, and I was tired of paying all that money with no control. So now, with me having my own server in front of me, I always tweak the crap out of it and have had absolutely no issues. I currently deploy this plugin, the latest commit BTW, not just the latest release, at my work with 18 employees using it heavily with hundreds of different calendars with thousands and thousands of events and there are ZERO errors thrown in my logs by this plugin that hinders its functionality at all. I do get 4 errors randomly that I specify in the Readme.md for this repo and even when those errors are logged, you don't know it because the task you perform is completed successfully. I only know the logs are there because I look at logs all day long.
.
I have been building, configuring and maintaining enterprise servers for over 25 years as my profession and about 10 years of building home servers not just for myself, but friends family and clients and think I know a thing or two and I am extremely confident it is not this plugin throwing that error but a configuration issue IMHO. 

Anyway, regardless if that is or is not the case, I need more info from you to even begin to figure this out.

Please provide the following at the bear minimum:
OS Flavor and Version
Available RAM
Webserver Name and Version
PHP Version
SQL Version
Roundcube Version
Nextcloud Version
I require the logs from everything I mentioned above as well as config files, with the exception of RAM of course.
I require a list of all plugins and their version numbers installed, not just enabled plugins, but all plugins within your plugin directory of Roundcube. That is a good start.

The more info you provide, the quicker and easier a solution can be found.

I thank you and hope you have a good evening
