### ISSUE TITLE
will this work on a multi-site shared server?

### ISSUE THREAD

**Issue by luvis** [texxasrulez/caldav_calendar#4]
first, thanks for the effort you put into this, truly appreciated!
I have a specific question because I'd like to install this on a shared server. But since the config needs to be changed to a fqdm I was wondering what happens if it's on a shared server with multiple domains and more than one nextcloud installation? Is it possible to use a place-holder like https://%{HTTP_HOST}/ or something like that? If not, would it be possible to do? Are their any other things I would need to consider?

**Comment by texxasrulez** [comment]
Cross Domains are tricky and I personally don't recommend to use them. Just makes things way more complicated than it has to be. Most experts out there recommend it not be used anyway for security reasons especially with sites running authenticated sessions. Plus it looks a little hinky, IMHO, to use different domains for shared services from the same provider ... 

There is no plan on implementing any such feature in this branch, but @Offerel and myself are working on a new branch to add more features and expand its compatibility to a wider choice of all the caldav flavors out there. 
It can be found here at [Caldav Calendar - Texas Edition](https://github.com/texxasrulez/caldav_calendar_te) .
Just as a reminder, this is and will be in Alpha Development for the foreseeable future and is not for faint of heart, but hey, that is half the fun of using Open Source Software for me. I like the challenge and it is slowly helping me become a more experienced coder. I am still at kiddy end of the pool, but will be in the deep end one way or the other.

I will have to discuss with @Offerel since we are a team on the new fork, but I can say for me, personally, this would be at the bottom of my TODO list if it makes the cut. 

I do thank you for your interest in this little project and hope you have a great week.
