### ISSUE TITLE
Non nextcloud caldav

### ISSUE THREAD

**Issue by ktpx** [texxasrulez/Caldav_Calendar#42]
Not an issue, but...im trying to phase out nextcloud, would this plugin work with something like Baikal, or other caldav supporting servers?

**Comment by winnertako** [comment]
I'm using with Davical...

**Comment by ktpx** [comment]
> I'm using with Davical...

I guess I will try it with Baikal...surprised there is no "default" caldav plugin in Roundcube.  But I see this plugin doesn't work with the new skin....

**Comment by ktpx** [comment]
Tried this with 1.14, and it seems to behave poorly.

**Comment by texxasrulez** [comment]
I have been busy lately, so I apologize for replying late, but honestly, I don't know. I am not a gifted programmer, just an old man who knows a little. I started this because I couldn't find a solution for nextcloud, which no calendar plugin would work, at least a little, out of the box, and just through blood, sweat and tears, got this to work with absolutely no help. 

Honesty I see no reason why something can not be achieved to support all CalDav servers. I would be down to devote my time on something that supports it all with a little help. I have mentioned this in the past, but I have had no takers.

I ask all who is willing to help.

**Comment by ktpx** [comment]
Thanks, no worry.
