### ISSUE TITLE
Calendar complains about "No driver name found in GPC." on pretty much every action.

### ISSUE THREAD

**Issue by wronan** [texxasrulez/Caldav_Calendar#45]
Taking advantage of the winter holidays I wanted to integrate my nextcloud calendar with roundcube at last. I stumbled upon this plugin, installed it but it gives me a hard time.

Whenever I try to create a new calendar it responds with "No driver name found in GPC." on the screen. I did some code digging and the error makes sense since actions try to detect the driver name via `calendar::get_driver_by_gpc()` which tries to extract it from the `_driver` or `driver` cookie/get/post param but no such param is sent.

I've checked a couple of last commits hoping that it got broken in some near past but couldn't find anything useful. How did it work before anyway?

My idea of a fix would be to send a `driver` param in every form (likely as a hidden input). This would also brought me closer to squeezing multi-driver support out of this code (I'd like to use calendars from both caldav and database backends at the same time) . From what I've seen there's no such feature currently, which makes me think why there is a possibility to configure multiple drivers (`calendar_driver` config option is an array) in the first place?

Q1: Is sending a `driver` param from the forms whenever it's necessary a good idea or am I missing something here?
Q2: If Q1=yes then would you accept such PR?
Q3: If Q2=yes then would you also accept also some other refactoring? (mostly naming conventions, indentation, stuff that would make the code more readable which in my dictionary means "stuff that would bring it closer to PSR")

PS
Merry Christmas :)

**Comment by texxasrulez** [comment]
I cannot recreate this issue. When I first started, that was a common error, but I have provided a fix for them. I would love help on this if you want to help out. That would be awesome. This last major update re-introduced some old behavior and the solutions provided for in past commits just doesn't cut it anymore. More eyes would definitely not hurt. I am going to dive back into the code after the holidays and plan on adding some other functionality I have been working on behind the scenes for a while now ... No spoilers
Thanks and have a great day

**Comment by texxasrulez** [comment]
Try downloading the latest commit. There were a few GPC Drivers error fixes left I hadn't pushed to commit. Let me know how it works. I did fix the annually recurring all-day events as well ...

**Comment by wronan** [comment]
Sorry man - just pulled from master and still `Application Error (500): No driver name found in GPC.` on new calendar. This problem is driver-neutral (happens on all of them).
Will dig into it tomorrow.

I will dig into it tomorrow but if you could do me a favor please investigate the request sent to create the new calendar (I'm interested how this `driver` param is sent; in the POST or GET, if even is sent at all). Thanks.

**Comment by trogper** [comment]
I have the same issue

**Comment by trogper** [comment]
@wronan I have the same issue, so I just created a cookie (in chrome devtools) 
with name 'driver' and value 'caldav'

**Comment by wronan** [comment]
Nice workaround :)

**Comment by texxasrulez** [comment]
This is a known thing. The latest commit was a major overhaul behind the hood and I missed a few required $driver that needed to be changed to $this->driver. That latest commit will fix.

**Comment by trogper** [comment]
Issue still present in latest commit, adding calendar yields "No driver name in GPC" error

**Comment by texxasrulez** [comment]
I have literally added, deleted, moved, copied, modified, downloaded, emailed, (pretty much everything I can think of that the plugin currently supports) 100's of time since this commit release with no GPC errors. I will post the common error I get (which I will add on the Readme of this repo for transparency and info) in my Roundcube log, but everything works perfect for me with the exception of All Day repeating events, which can be worked around by unchecking the all day box. I figured it out once and I will figure it out again to have the all day event working.

Now to clarify your comment above "adding calendar yields "No driver name in GPC" error", with an emphasis on the word "ADDING". Are you trying to create a new calendar within Roundcube Calendar GUI? If you are, unfortunately at this point in time it is not possible to create a new calendar within Roundcube. You must create it within Nextcloud GUI for it to work. Once creating your new calendar within Nextcloud GUI, you go back to your Roundcube Calendar tab, it will automatically add and sync your new calendar you just created. I know, a pain in the Gluteus Maximus, but it is a WIP.

The ability to create a calendar from the RoundCube Calendar GUI is a major wish and is high on my list ... Just haven't figured it out yet.

My Common (and only at the moment) error in my log pertaining to this plugin:

[29-Jan-2020 21:02:25 America/Los_Angeles] PHP Warning:  feof() expects parameter 1 to be resource, null given in /path_to_roundcube/plugins/calendar/lib/vendor/sabre/vobject/lib/Parser/MimeDir.php on line 245
[29-Jan-2020 21:02:25 America/Los_Angeles] PHP Warning:  fgets() expects parameter 1 to be resource, null given in /path_to_roundcube/plugins/calendar/lib/vendor/sabre/vobject/lib/Parser/MimeDir.php on line 247
[29-Jan-2020 21:02:25 America/Los_Angeles] PHP Warning:  feof() expects parameter 1 to be resource, null given in /path_to_roundcube/plugins/calendar/lib/vendor/sabre/vobject/lib/Parser/MimeDir.php on line 249
[29-Jan-2020 21:02:25 -0800]: <179594f3> PHP Error: iCal data parse error: Error reading from input stream in /path_to_roundcube/plugins/libcalendaring on line 163 (POST /mail/?_task=calendar&_action=refresh)

From what I have learned, this is common when the end of line is not defined properly using  \r\n, but as far as I can see within code, all is well on that front, but still looking. LOTS of lines to look at.
