### ISSUE TITLE
Sabre/vobject not found in libvcalendar.php

### ISSUE THREAD

**Issue by trogper** [texxasrulez/Caldav_Calendar#48]
`libvcalendar.php` in libcalendaring requires sabre/vobject, but the dependency is not included. This causes error 500 when vieweing any mail.
I have installed it using `composer install --no-dev` in libcalendaring and added `require 'vendor/autoload.php';` to the top of `libvcalendar.php`
I have installed the plugin as instructed: unzip and copy folders, then add calendar to plugins.

Other than that, I'm having issues with opening an email containing .ics file, accepting, rejecting invitation, basically doing anything.
Error log shows "Uncaught Error: Call to a member function remove_event() on null", $driver being null. Replacing `$driver` with `$this->driver` helps.
I'm using davical on the same host (but separate hostname) as caldav backend, tried with php7.{0,3,4}.

**Comment by texxasrulez** [comment]
Sorry for delay on responding. Been a busy year so far for me at my job that pays the bills for me. Anyway, I have already done some fixing on that, just been busy as stated before and wanted to do more testing to make sure I have found all the drivers that need fixing. You are correct on how to provide a fix to on that. Easy as Pie. I should have all of this specific code fix done. Please download latest commit for fixed commit and I thank you for your submittal.

**Comment by trogper** [comment]
both issues are still present. If I don't add `require 'autoload.php'`, I can not open any mail (error 500, as described). Where do you have `sabre/vobject` installed in your roundcube? I have manually installed it in `libcalendaring/vendor`

the second issue was encountered when opening email with .ics file, so I reverted to the previous, manually fixed version of calendar.php
```
  thrown in /usr/share/roundcube/plugins/caldav_calendar/calendar/calendar.php on line 2853
[24-Jan-2020 13:36:49 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function get_event() on null in /usr/share/roundcube/plugins/caldav_calendar/calendar/calendar.php:2853
Stack trace:
#0 /usr/share/roundcube/plugins/caldav_calendar/calendar/calendar.php(2875): calendar->find_event()
#1 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(494): calendar->event_itip_status()
#2 /usr/share/roundcube/index.php(294): rcube_plugin_api->exec_action()
#3 {main}
  thrown in /usr/share/roundcube/plugins/caldav_calendar/calendar/calendar.php on line 2853
```
What is the issue with `$this->driver`, why are you replacing it with just `$driver`?
Anyways thanks for providing this plugin

**Comment by texxasrulez** [comment]
This plugin uses it's own sabre, which is located at /roundcube_install_dir/plugins/calendar/lib/vendor/sabre and is included within download of this repo and should automatically copy itself there.

A few releases back, it was located at /roundcube_install_dir/plugins/libcalendaring/lib/OldSabre (which in reality would be the sabre root) which is where FasterIT's version of the caldav calendar had it from the beginning of me forking this and their reasoning was to keep compatible with other sabre dependent plugins (blind-coders Carddav [plugin](https://github.com/blind-coder/rcmcarddav) in particular if memory serves) but I have since really changed a lot and have had no issues and no issues with blind-coders carddav (which is awesome BTW). Try deleting the sabre (or at least renaming the directory) within your libcalendaring direcory and see if that solves your issue.
Let me know please.
Thank you for your interest.
