### ISSUE TITLE
Error when trying to display the calendar - PHP Error: iCal data parse error

### ISSUE THREAD

**Issue by uli-heller** [texxasrulez/Caldav_Calendar#52]
I'm currently trying to setup the plugin. I'm using Nextcloud 17 for the calendar and version 0.6.0 of the roundcube plugin. The calendar app within nextcloud is version 2.0.1.

When clicking on the calendar icon within roundcube, I'm getting these messages:

console.log:

```
...
24-Jan-2020 08:29:27 +0100]: <8465uisl> caldav_driver: Created event "38".
[24-Jan-2020 08:29:27 +0100]: <8465uisl> caldav_driver: Created event "39".
[24-Jan-2020 08:29:27 +0100]: <8465uisl> caldav_driver: Created event "40".
[24-Jan-2020 08:29:27 +0100]: <8465uisl> caldav_driver: Created event "41".
```

errors.log:

```
[24-Jan-2020 08:29:27 +0100]: <8465uisl> PHP Error: iCal data parse error: Object validation failed: missing mandatory object properties in /var/www/roundcubemail-1.4.1/plugins/libcalendaring on line 165 (GET /roundcube/?_task=calendar)
[24-Jan-2020 08:31:26 Europe/Berlin] PHP Fatal error:  Maximum execution time of 120 seconds exceeded in /var/www/roundcubemail-1.4.1/plugins/calendar/drivers/caldav/caldav_driver.php on line 671
```

Any ideas?

**Comment by texxasrulez** [comment]
Honestly, I do not have any ideas. At the moment I do not have any errors of your nature. I will add that I have found while rewriting and troubleshooting things that it is a good measure to delete the caldav calenar items in your Roundcube Database. This will not effect your Nextcloud calendar and upon next refresh of your calendar tab within Roundcube will add your calendars back. So if you would please, empty your caldav_attachments, caldav_calendars and caldav_events and post your error logs from there.

**Comment by uli-heller** [comment]
Hi Gene, I actually deleted those three tables this morning and
recreated them via mysql.init.sql. Within the "errors.log" only the two
lines show up. Shall I repeat the procedure? Can I activate extended
logs somehow? Thx + best regards, Uli 

Am 2020-01-24 08:58, schrieb Gene Hawkins:

> Honestly, I do not have any ideas. At the moment I do not have any errors of your nature. I will add that I have found while rewriting and troubleshooting things that it is a good measure to delete the caldav calenar items in your Roundcube Database. This will not effect your Nextcloud calendar and upon next refresh of your calendar tab within Roundcube will add your calendars back. So if you would please, empty your caldav_attachments, caldav_calendars and caldav_events and post your error logs from there. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/texxasrulez/Caldav_Calendar/issues/52?email_source=notifications&amp;email_token=AAMZQZSN3XTRC32WDHVEMIDQ7KNSLA5CNFSM4KLCIAP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJ2AQHA#issuecomment-578029596
[2]

**Comment by uli-heller** [comment]
Closing without a comment is quite disappointing but I'll arrange with it :(

**Comment by texxasrulez** [comment]
I do not remembering closing this, but hey, I am an old man and those late nights gets me sometimes. I don't like to be rude to anyone, I wouldn't just close without an explanation at least, so I do apologize, but I honestly do not remember closing this. Senior Moment Excuse.

Just copy and paste your logs right here (hide sensitive things, ie file structures, URL's any other identifiable info) so all can see and the more minds on something the better. Thank you and I wait for your log entries.

**Comment by uli-heller** [comment]
Thanks a lot, that's quite a relief for me. I'll do as proposed, it will
probably take a couple of hours/days...

**Comment by uli-heller** [comment]
Here is what I did:
1. Delete the data from the tables
    ```
    MariaDB [roundcubemail]> delete from caldav_attachments;
    Query OK, 0 rows affected (0.00 sec)
    
    MariaDB [roundcubemail]> delete from caldav_calendars;
    Query OK, 10 rows affected (0.04 sec)
    
    MariaDB [roundcubemail]> delete from caldav_events;
    Query OK, 0 rows affected (0.00 sec)
     ```
2. Delete the logs
3. Reboot the server
4. Access the calendar
5. Wait a little bit
6. Watch the log files growing
7. errors.log (contains just one line):
    ```
    uli@ulinuc:/tmp$ cat errors.log 
    [30-Jan-2020 19:09:34 +0100]: <f5m13j1i> PHP Error: iCal data parse error: Object validation failed: missing mandatory object properties in /var/www/roundcubemail-1.4.1/plugins/libcalendaring on line 165 (GET /roundcube/?_task=calendar)
    uli@ulinuc:/tmp$ 
    ```
8. console.log - attached
[console.log](https://github.com/texxasrulez/Caldav_Calendar/files/4135581/console.log)

**Comment by texxasrulez** [comment]
In reference to your post above "www/roundcubemail-1.4.1/plugins/libcalendaring on line 165", is very strange. It should have "www/roundcubemail-1.4.1/plugins/libcalendaring/FILENAME.php on line 165". 
Did you strip out the filename, or is that how it output to your log? It should be either libcalendaring.php or libvcalendar.php where I have FILENAME.php

It has me thinking about a possibility of incompatible/un-needed files if you did not strip the filename yourself.

Indulge me if you wouldn't mind, but if you have been updating via ssh/ftp'ing and overwriting existing directories/files (which is usually the way to go), or composer updater to update, then you will need to do a totally clean install because I made MAJOR structure changes with Release 0.6.0 a clean install should be needed.

 I will explain a bit here.  First, it is totally my fault for not specifying a fresh install is needed when upgrading to 0.6.0 from 0.5.1 because of those MAJOR changes. In all honesty, I didn't think about it because I usually always update all plugins I use via a method I will describe below. Sorry about that to all, I am pulling my old man card out again as an excuse, but anyway, I will ramble a bit and then lay it out how different the changes are and how I would update it and why ... 

The sabre structure is wildly different from the two versions. Releases prior to 0.6.0, the sabre is located within /plugins/libcalendaring/lib/OldSabre directory. I didn't do it that way, that was how I found it when I forked this several years ago. Since version 0.6.0 sabre is now located within /plugins/calendar/lib/vendor/sabre where it should've been all along. 

I have big plans in the future for more features and such (got the wishlist on the Reamde.md), so I basically started over using Kolab (v3.5.2) calendar base code and incorporated my few additions and the version of caldav driver I have been maintaining for a while now because I thought would be quick and easy way to get this up to date so I could concentrate on my wishlist goals. It did save me a lot of time, but little driver errors popped up here and there and took me a while to fix those, which should be good to go, or at least for me and my users it is totally good now. With lots of time, lots of typing and probably even more cursing and a bit of luck, hopefully ;-) I can create something that will be totally different from all other calendar plugins out there with extra authentications (Google Calendars just to name one of many), multiple version support for caldav (baikal, davical, etc) flavors and true integration between Roundcube and target dav provider so one could create that new calendar from RC GUI without having to do within Nextcloud GUI (or others in future releases).

OK, Installation Recommendation: (Repeating myself here, but this is how I update ALL plugins I use, not just the ones I maintain)

Rename plugin folders for calendar, libcalendaring and libkolab to something else, I usually just put a 2 at end of directory name. I say this so you can back out easily if you wish. Rest assured you will lose nothing with this method. 
Download the latest commit (Not a half an hour old at the time of posting this reply), unzip it, and upload via sFTP into your plugin directory as if if were the first time installing this plugin. 
I also recommend using the latest config.inc.php.dist provided with latest commit since I have added things to that file recently as well.  
Rename config.inc.php.dist to config.inc.php and edit the URL's tailored for your specific Nextcloud install location.  

Backup your database tables caldav_calendars, caldav_events and caldav_attachments, if you have any attachment and then Truncate those same tables. 

Once that is done, login to your Roundcube, click on calendar tab, give a quarter to half a minute and it should sync all your calendars from Nextcloud and repopulate your database tables except for the attachments. Those have to be redone for each event. You should be good to go outside of 2 very minor issues I will mention below.

If you find yourself worse after this method, which you shouldn't, just delete the recently uploaded plugin directories calendar, libcalendaring and libkolab and rename your earlier renamed folders back to original, import your backup of you caldav_ tables, and you are right back where we began and more info will be needed then. System logs, php version, sql version, OS, RC version, Nextcloud Version logs etc etc. The more info you provide will help out tremendously .... 

I will add that I am currently using the latest commit in production at my work using RC1.4.2 & Nextcloud 18.0, and outside of the All Day Recurring event issue I re-opened last night (which there is a dirty little workaround / temp fix for that until I can figure out a permanent fix) and an occasional error log entry of a grouping of 4 errors in my Roundcube errors.log. The 4 error grouping seems to happen randomly with no rhyme or reason and only a few times a day with 18 fellow employees all using the calendar with shared calendars and itip invitations, accepting, rejecting, blah blah. In simple terms, we use the crap out of this thing and 95% of the time, no error log entries are logged when creating, editing, downloading, sending, copying, itip inviting importing, or exporting (pretty much every button I can think of to push when testing) of events. You will not know when these 4 errors are logged either, as it has no ill effect on what you are doing with your events. It does what is asked and successfully completes the tasks asked. Only when you check your error log (if you are like me, you check it 100 times a day) is when you will see the errors. I call them Schrödinger's Errors .. B-)

Whew, that was long winded, anyway, I have done this MANY MANY MAAANY times in my life and sometimes just starting over and doing a fresh install can perform miracles not to mention saved headaches and pain.

This upgrade method will take no longer than 5 minutes if you got a decent connection and I would truly recommend you give this a shot and just try a clean install for good measure. I am confident you will be good to go as long as you are using this plugin as intended, and documented, and use only with Nextcloud as that is the only backend I support at the moment.

As I have posted many times, I wished I could make it work for all, but at this point in time, I don't have the resources and not to mention, NO time. I am using my limited time on finding a fix for the all day recurring bug. When that is fixed, I will begin to slowly develop and add features no other calendar plugin is offering at the moment.

Anyway, this old man is gonna quit rambling and go for now. Let me know how you did update this plugin prior to this and if you tried the fresh install and if it worked for you. I did type this long winded for another reason outside of my funny excuse of being old but I will add this install method for upgrading to version 0.6.x to the Readme because it needs to be there. Good Luck

P.S.
I have added the 4 errors I mentioned above at the bottom of the Readme.md in the root of this Plugin Repo.

**Comment by uli-heller** [comment]
I'll read your instructions right away. This in advance: I did not modify the logs in any way, the lines do show up as mentioned before.

I derived the installation from a previous one where I used the kolab calendar. Maybe this is something causing trouble?

I'll read your post now and take the actions mentioned within. Please be patient, will probably take a couple of hours...

Thanks + best regards, Uli

**Comment by texxasrulez** [comment]
Well if you didn't strip it, which is not uncommon, and installed this plugin by overwriting a totally different calendar plugin, then this will DEFINITELY fix your particular problem. Best of luck to ya .. 

On a personal note, just wondering where you are from? You do not have to tell me, but I am a curious individual and am just wondering if I have ever been in your neck of the woods when I was in the Navy as a youngster. I never met a stranger upon arrival and always left friends upon departure. Always had good times at every port visit I had ...

**Comment by uli-heller** [comment]
I read your explanations - thanks a lot for all your work.

To me, it is not a problem to start over. I do not have any
"serious" data within the roundcube instance I use for testing
the calendar plugin.

I understand that you don't have the time for providing fool proofed
update procedures. To me, they aren't necessary at the moment.

I updated my nextcloud instance to version 18 a few moments ago, so
all following tests will run against that version. Version 17 is gone
for me. So we are on the same page related to this.

I also updated my roundcube instance to 1.4.2.

I also downloaded the latest "master" version from your plugins.
Modified 3 hours ago as of this writing.

Afterwards, I

* stopped my apache httpd instance
* deleted all data from within caldav_{attachments,calendars,events}
* moved some plugins folders (calendar, libcalendaring, libkolab)
   as proposed appending a "2"
* unzip the master version of your plugin
* within plugins/calendar: use config.inc.php.dist as new base
   for my calendar configuration - modified these:
     * calendar_crypt_key
     * calendar_caldav_debug
     * calendar_ical_debug
     * caldav_url
* truncated console.log and errors.log
* started my apache httpd instance

Roundcube is running OK.

First impression: The calendar looks much better now. I see some
of the nextcloud calendars within roundcube. I also see lots of events
from the nextcloud calendar. At the moment, it is still "loading" (in 
German: "Wird geladen...") for a pretty long time and I don't see 
anything within console.log and errors.log.

I'll do some more observations and analysis over the day and update the 
ticket afterwards.

Thanks a lot for your help and patience!

Am 2020-01-31 06:44, schrieb Gene Hawkins:

**Comment by uli-heller** [comment]
Am 2020-01-31 08:48, schrieb Gene Hawkins:

> Well if you didn't strip it, which is not uncommon, and installed this 
> plugin by overwriting a totally different calendar plugin, then this 
> will DEFINITELY fix your particular problem. Best of luck to ya ..

Yes, it looks much better now. Sorry for being stupid upon updating...

> On a personal note, just wondering where you are from? You do not have 
> to tell me, but I am a curious individual and am just wondering if I 
> have ever been in your neck of the woods when I was in the Navy as a 
> youngster. I never met a stranger upon arrival and always left friends 
> upon departure. Always had good times at every port visit I had ...

I'm living in Germany in Kornwestheim, a small town near Stuttgart
where you can get nice cars.

In former times, lots of American soldiers used to live here. We had two 
big US barracks in town but they are gone for decades now.

**Comment by uli-heller** [comment]
The issue is fixed, memo to me: Always delete/rename plugins/{calendar,libcalendaring,libkolab} when updating

**Comment by texxasrulez** [comment]
It is all good. I have been foolin' around with Roundcube since its initial release in 2008 and have used TONS of plugins. I am kinda a pro at this stage on things. One advantage of getting old is acquiring all that knowledge. At least we got you up and running.

I never made it to Germany. I mostly sailed around the Pacific and Indian Oceans. Been all around the Orient, the Middle East, Western Africa and Australia (my favorite port visit). I did float half way around the world on my ship 3 times and back again. My last cruise, and 4th cruise, I sailed to the Persian Gulf and then got flown out from there because my time was up and I was getting parolled.  I then got to completely circumnavigate the globe that go round. Half by Sea and half by air. I did have a pit stop in Italy, only time in Europe, for three hours because our plane had issues. It turned out great because I was hanging out with a dozen or better USO Show Girls that were on that military flight with me and we had an AWESOME 3 hours there. One day I will make it to Europe and travel all over. Get me some of those chocolates with liquor in them. I have a buddy that his family immigrated from Germany and his parents still visit and bring those back for us. Good Stuff. I do give the German's credit on building a damn fine automobile, but I still prefer my late 60's Chevy Muscle Cars .. I am old and stuck in my ways .. 

Anyway, thanks for your interest and hope all keeps humming along for you.
