### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by RUDI-TERROR** [texxasrulez/Caldav_Calendar#54]
Hi,
in the config i set a static user, because i don't use my email-adress in nextcloud:

 $config['calendar_preinstalled_calendars'] = array(
    'Nextcloud' => array(
                    'driver'       => 'caldav',
                    'name'         => '%n',
                    'caldav_user'  => 'Marco',
                    'caldav_pass'  => 'xxx',
                    'caldav_url'   => 'https://xxx.de/remote.php/dav/calendars/Marco/',
                    'color'        =>  '',
                    'showAlarms'   => 1));
?>

Unfortuly, I get a http-401 error. Can you give me a tipp, what i do wrong?

[26-Jan-2020 11:07:26 +0100]: <um7pm7gn> DAV Error: HTTP error: 401 in /var/www/roundcubemail/plugins/calendar/lib/vendor/sabre/dav/lib/DAV/Client.php on line 231 (POST /?_task=calendar&_action=refresh)

**Comment by texxasrulez** [comment]
You need to change your 'caldav_url' to https://xxx.de/remote.php/dav/calendars/%u/ .

**Comment by Offerel** [comment]
Hi there,

sorry for hijacking this issue. But I get the same error message in my log file. My configuration looks like this:

```
$config['calendar_preinstalled_calendars'] = array(
'SabreDAV' => array(
'driver' => 'caldav',
'name' => '',
'caldav_user' => '%u',
'caldav_pass' => '%p',
'caldav_url' => 'http://localhost:81/dav/calendars/%u/',
'color' => '',
'showAlarms' => 1));
```

Only difference is that the backend is a pure SabreDAV. It is also used in the Backend of NextCLoud. Using SabreDAV standalone is much faster than NetxCloud, therefore this variant. Initially a connection is established. The calendars are created in my case and from all calendars appointments are also "imported". This error seems to occur only during refresh.

Notes on the above URL: This URL is only internally accessible from Roundcube. I wanted to avoid the transport over the external network. Therefore the transmission is unencrypted and via port 81, which avoids some overhead. As the creation of the calendar demonstrates, it seems to work. 

Nevertheless I get the 401 error during refresh, as if the authentication had expired or would not take place every time. What also surprises me is that I get the refresh every 60 seconds. Unfortunately I have not found a way to set a time how often or when a new refresh should start. Since a refresh currently takes 37 seconds, the server is super busy. It seems that not all dates have been imported yet.

**Comment by Offerel** [comment]
OK, got a explanation for the 401 error. After comparing the timestamp of the 401 error with the timestamps in /var/log/php/error.log, i found the following entry's with identical timestamp:
```
[05-Feb-2020 07:43:51 Europe/Berlin] imap_open(): Couldn't open stream {imap.strato.de:993/imap/ssl}
[05-Feb-2020 07:43:51 Europe/Berlin] IMAP protocol error: Authentication cancelled
[05-Feb-2020 07:43:51 Europe/Berlin] IMAP Authentication cancelled
```

Since user and password is shared between this connections and stream couldn't opened to the IMAP server for authentication, credentials are no longer valid for DAV request. It seems that for every DAV request an IMAP auth request is made before. So this must be flooding the IMAP server and as DDOS prevention they block this much request in such a short interval. Since the specified IMAP server isn't under my control, i have to find a way do not spam the IMAP server with so much requests. Maybe we can cache the auth result for a while or re-use the authentication or a earlier established connection. This should also speed up syncing a lot.

I will have a look in the code, if i found a solution. Would be nice, if you can do the same. Maybe we find the solution faster together.

**Comment by Offerel** [comment]
Set now `private $sync_period = 600; // seconds` in `calendar/drivers/caldav/caldav_driver.php` on line 51. This prevents a real sync occurring to often. 600 means 10 minutes in this case. With this, i didn't spam the IMAP server anymore.

Set in Roundcube preferences the refresh interval to 3 Minutes. This was by 1 Minute eg. the 60 seconds interval i could see in the logfile. Conclusion: We should add a option to either set the refresh_interval (`$config['refresh_interval'] = 60;`) temporary to a higher value (if possible on plugin level) or to remove the automatic refresh, if the plugin is loaded. I tend to use the later approach, since in my opinion refreshing isn't needed permanent for this plugin and it is refreshed every time the plugin is loaded automatically. This could be done with `$rcmail->output->set_env('refresh_interval', 0);` in the plugin init function. Will try this in a fork this evening.

*loud thinking*, if i could set it to 0, i could also define other values > eg. a option for this plugin should also work. 

_Please let me know, if refreshing is really needed. If so we can add a option in config file and in settings gui._

**Comment by Offerel** [comment]
I have created a fork and made a dev branch. If you are ok with this, i can make a pull request, or maybe different pull requests, if thats better for you.

**Comment by texxasrulez** [comment]
I welcome all input. This is the development branch so all pull requests are welcome on this. It just means we are in it together now.  :-) 

Let's create something awesome.
